In [1]:
# libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
df = pd.read_parquet("../../data/final.parquet")
df.head()

,order_id,product_id,add_to_cart_order,reordered,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_name,aisle_id,department_id,aisle,department
0,2,33120,1,1,202279,prior,3,5,9,8.0,Organic Egg Whites,86,16,eggs,dairy eggs
1,2,28985,2,1,202279,prior,3,5,9,8.0,Michigan Organic Kale,83,4,fresh vegetables,produce
2,2,9327,3,0,202279,prior,3,5,9,8.0,Garlic Powder,104,13,spices seasonings,pantry
3,2,45918,4,1,202279,prior,3,5,9,8.0,Coconut Butter,19,13,oils vinegars,pantry
4,2,30035,5,0,202279,prior,3,5,9,8.0,Natural Sweetener,17,13,baking ingredients,pantry

In [6]:
df

,order_id,product_id,add_to_cart_order,reordered,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_name,aisle_id,department_id,aisle,department
0,2,33120,1,1,202279,prior,3,5,9,8.0,Organic Egg Whites,86,16,eggs,dairy eggs
1,2,28985,2,1,202279,prior,3,5,9,8.0,Michigan Organic Kale,83,4,fresh vegetables,produce
2,2,9327,3,0,202279,prior,3,5,9,8.0,Garlic Powder,104,13,spices seasonings,pantry
3,2,45918,4,1,202279,prior,3,5,9,8.0,Coconut Butter,19,13,oils vinegars,pantry
4,2,30035,5,0,202279,prior,3,5,9,8.0,Natural Sweetener,17,13,baking ingredients,pantry
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33819101,3421063,14233,3,1,169679,train,30,0,10,4.0,Natural Artesian Water,115,7,water seltzer sparkling water,beverages
33819102,3421063,35548,4,1,169679,train,30,0,10,4.0,Twice Baked Potatoes,13,20,prepared meals,deli
33819103,3421070,35951,1,1,139822,train,15,6,10,8.0,Organic Unsweetened Almond Milk,91,16,soy lactosefree,dairy eggs
33819104,3421070,16953,2,1,139822,train,15,6,10,8.0,Creamy Peanut Butter,88,13,spreads,pantry
33819105,3421070,4724,3,1,139822,train,15,6,10,8.0,Broccoli Florettes,32,4,packaged produce,produce

In [8]:
# sort users chronologically
df = df.sort_values(by=['user_id', 'order_number', "add_to_cart_order"], ascending=True)
df

,order_id,product_id,add_to_cart_order,reordered,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_name,aisle_id,department_id,aisle,department
24076664,2539329,196,1,0,1,prior,1,2,8,NaN,Soda,77,7,soft drinks,beverages
24076665,2539329,14084,2,0,1,prior,1,2,8,NaN,Organic Unsweetened Vanilla Almond Milk,91,16,soy lactosefree,dairy eggs
24076666,2539329,12427,3,0,1,prior,1,2,8,NaN,Original Beef Jerky,23,19,popcorn jerky,snacks
24076667,2539329,26088,4,0,1,prior,1,2,8,NaN,Aged White Cheddar Popcorn,23,19,popcorn jerky,snacks
24076668,2539329,26405,5,0,1,prior,1,2,8,NaN,XL Pick-A-Size Paper Towel Rolls,54,17,paper goods,household
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32545756,272231,40603,4,0,206209,train,14,6,14,30.0,Fabric Softener Sheets,75,17,laundry,household
32545757,272231,15655,5,0,206209,train,14,6,14,30.0,Dark Chocolate Mint Snacking Chocolate,45,19,candy chocolate,snacks
32545758,272231,42606,6,0,206209,train,14,6,14,30.0,Phish Food Frozen Yogurt,37,1,ice cream ice,frozen
32545759,272231,37966,7,0,206209,train,14,6,14,30.0,French Baguette Bread,112,3,bread,bakery
32545760,272231,39216,8,1,206209,train,14,6,14,30.0,Original Multigrain Spoonfuls Cereal,121,14,cereal,breakfast

In [11]:
# create prediction target - one week or less
df['next_order_within_7_days'] = np.where(df['days_since_prior_order'] <= 7, 1, 0)
df.head()

,order_id,product_id,add_to_cart_order,reordered,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_name,aisle_id,department_id,aisle,department,target,next_order_within_7_days
24076664,2539329,196,1,0,1,prior,1,2,8,NaN,Soda,77,7,soft drinks,beverages,0,0
24076665,2539329,14084,2,0,1,prior,1,2,8,NaN,Organic Unsweetened Vanilla Almond Milk,91,16,soy lactosefree,dairy eggs,0,0
24076666,2539329,12427,3,0,1,prior,1,2,8,NaN,Original Beef Jerky,23,19,popcorn jerky,snacks,0,0
24076667,2539329,26088,4,0,1,prior,1,2,8,NaN,Aged White Cheddar Popcorn,23,19,popcorn jerky,snacks,0,0
24076668,2539329,26405,5,0,1,prior,1,2,8,NaN,XL Pick-A-Size Paper Towel Rolls,54,17,paper goods,household,0,0

,order_id,product_id,add_to_cart_order,reordered,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_name,aisle_id,department_id,aisle,department,next_order_within_7_days
24076664,2539329,196,1,0,1,prior,1,2,8,NaN,Soda,77,7,soft drinks,beverages,0
24076665,2539329,14084,2,0,1,prior,1,2,8,NaN,Organic Unsweetened Vanilla Almond Milk,91,16,soy lactosefree,dairy eggs,0
24076666,2539329,12427,3,0,1,prior,1,2,8,NaN,Original Beef Jerky,23,19,popcorn jerky,snacks,0
24076667,2539329,26088,4,0,1,prior,1,2,8,NaN,Aged White Cheddar Popcorn,23,19,popcorn jerky,snacks,0
24076668,2539329,26405,5,0,1,prior,1,2,8,NaN,XL Pick-A-Size Paper Towel Rolls,54,17,paper goods,household,0